version: "3.9"

services:
  web:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app                    
      - node_deps:/app/node_modules 
    environment:
      - NEXT_TELEMETRY_DISABLED=1   
      - NODE_ENV=development        

volumes:
  node_deps: {}
  