version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: frontend.Dockerfile   # ← 変更
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_deps:/app/node_modules
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://api:8000
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=development
    depends_on:
      - api                               # API が先に立つまで待機

  api:
    build:
      context: .
      dockerfile: backend.Dockerfile      # ← 新規
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./authentication:/app/authentication
      - ./main.py:/app/main.py
      - ./.env:/app/.env                  # AWS/Cognito 設定など
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=http://localhost:3000

volumes:
  node_deps: {}
