'use client';

import { useState, useEffect, useContext } from 'react';
import { UserContext } from '@/app/contexts/UserContext';
import { Ticket, User, Calendar, Copy, CheckCircle } from 'lucide-react';

interface Coupon {
  id: number;
  code: string;
  name: string;
  description?: string;
  discountType: string;
  discountValue: number;
  minAmount?: number;
  maxUses?: number;
  currentUses: number;
  isActive: boolean;
  expiresAt?: string;
  autoGenerated: boolean;
}

export default function ProfilePage() {
  const userContext = useContext(UserContext);
  const user = userContext?.user;
  const [coupons, setCoupons] = useState<Coupon[]>([]);
  const [loading, setLoading] = useState(true);
  const [copiedCode, setCopiedCode] = useState<string | null>(null);

  useEffect(() => {
    if (user?.id) {
      fetchUserCoupons();
    }
  }, [user]);

  const fetchUserCoupons = async () => {
    try {
      const response = await fetch(`/api/users/coupons?userId=${user?.id}`);
      if (response.ok) {
        const data = await response.json();
        if (data.success) {
          setCoupons(data.coupons || []);
        }
      }
    } catch (error) {
      console.error('Error fetching coupons:', error);
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = async (code: string) => {
    try {
      await navigator.clipboard.writeText(code);
      setCopiedCode(code);
      setTimeout(() => setCopiedCode(null), 2000);
    } catch (error) {
      console.error('Failed to copy code:', error);
    }
  };

  if (!user) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <User className="w-12 h-12 mx-auto mb-4 text-gray-400" />
          <h2 className="text-xl font-semibold text-gray-900 mb-2">Please Login</h2>
          <p className="text-gray-600">You need to be logged in to view your profile.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900">My Profile</h1>
          <p className="text-gray-600 mt-2">Manage your account and view your benefits</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* User Info */}
          <div className="lg:col-span-1">
            <div className="bg-white rounded-lg shadow p-6">
              <div className="flex items-center mb-4">
                <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center">
                  <User className="w-6 h-6 text-blue-600" />
                </div>
                <div className="ml-4">
                  <h2 className="text-lg font-semibold text-gray-900">
                    {user.firstName} {user.lastName}
                  </h2>
                  <p className="text-sm text-gray-500">{user.email}</p>
                </div>
              </div>
              
              <div className="space-y-3 text-sm">
                <div>
                  <span className="text-gray-500">Major:</span>
                  <p className="font-medium">{user.major}</p>
                </div>
                <div>
                  <span className="text-gray-500">Graduation Year:</span>
                  <p className="font-medium">{user.graduationYear}</p>
                </div>
                                 <div>
                   <span className="text-gray-500">Member Since:</span>
                   <p className="font-medium">
                     {user.joinedAt ? new Date(user.joinedAt).toLocaleDateString() : 'Unknown'}
                   </p>
                 </div>
              </div>
            </div>
          </div>

          {/* Coupons Section */}
          <div className="lg:col-span-2">
            <div className="bg-white rounded-lg shadow">
              <div className="px-6 py-4 border-b border-gray-200">
                <div className="flex items-center">
                  <Ticket className="w-5 h-5 text-purple-600 mr-2" />
                  <h2 className="text-lg font-semibold text-gray-900">My Discount Coupons</h2>
                </div>
                <p className="text-sm text-gray-600 mt-1">
                  Earned from event participation and feedback
                </p>
              </div>
              
              <div className="p-6">
                {loading ? (
                  <div className="text-center py-8">
                    <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-purple-600 mx-auto"></div>
                    <p className="mt-2 text-gray-600">Loading coupons...</p>
                  </div>
                ) : coupons.length === 0 ? (
                  <div className="text-center py-12">
                    <Ticket className="w-12 h-12 mx-auto mb-4 text-gray-300" />
                    <h3 className="text-lg font-medium text-gray-900 mb-2">No Coupons Yet</h3>
                    <p className="text-gray-600 mb-4">
                      Participate in events and fill out feedback forms to earn discount coupons!
                    </p>
                    <a
                      href="/events"
                      className="inline-flex items-center gap-2 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700"
                    >
                      <Calendar className="w-4 h-4" />
                      Browse Events
                    </a>
                  </div>
                ) : (
                  <div className="space-y-4">
                    {coupons.map((coupon) => {
                                             const isExpired = coupon.expiresAt ? new Date(coupon.expiresAt) < new Date() : false;
                      const isUsedUp = coupon.maxUses && coupon.currentUses >= coupon.maxUses;
                      const isAvailable = coupon.isActive && !isExpired && !isUsedUp;
                      
                      return (
                        <div
                          key={coupon.id}
                          className={`border rounded-lg p-4 ${
                            isAvailable ? 'border-green-200 bg-green-50' : 'border-gray-200 bg-gray-50'
                          }`}
                        >
                          <div className="flex items-start justify-between">
                            <div className="flex-1">
                              <div className="flex items-center gap-2 mb-2">
                                <h3 className={`font-medium ${isAvailable ? 'text-green-900' : 'text-gray-700'}`}>
                                  {coupon.name}
                                </h3>
                                {coupon.autoGenerated && (
                                  <span className="px-2 py-1 bg-blue-100 text-blue-700 text-xs rounded">
                                    Earned
                                  </span>
                                )}
                                {!isAvailable && (
                                  <span className="px-2 py-1 bg-red-100 text-red-700 text-xs rounded">
                                    {isExpired ? 'Expired' : isUsedUp ? 'Used Up' : 'Inactive'}
                                  </span>
                                )}
                              </div>
                              
                              <div className="flex items-center gap-4 mb-2">
                                <div className={`flex items-center gap-2 ${isAvailable ? 'text-green-800' : 'text-gray-600'}`}>
                                  <code className="px-2 py-1 bg-white border rounded font-mono text-sm">
                                    {coupon.code}
                                  </code>
                                  <button
                                    onClick={() => copyToClipboard(coupon.code)}
                                    className="p-1 hover:bg-white hover:bg-opacity-50 rounded"
                                    disabled={!isAvailable}
                                  >
                                    {copiedCode === coupon.code ? (
                                      <CheckCircle className="w-4 h-4 text-green-600" />
                                    ) : (
                                      <Copy className="w-4 h-4" />
                                    )}
                                  </button>
                                </div>
                                
                                <div className={`text-sm font-medium ${isAvailable ? 'text-green-700' : 'text-gray-600'}`}>
                                  {coupon.discountType === 'percentage' 
                                    ? `${coupon.discountValue}% off`
                                    : `$${coupon.discountValue} off`
                                  }
                                  {coupon.minAmount && ` (min $${coupon.minAmount})`}
                                </div>
                              </div>
                              
                              {coupon.description && (
                                <p className={`text-sm ${isAvailable ? 'text-green-700' : 'text-gray-600'} mb-2`}>
                                  {coupon.description}
                                </p>
                              )}
                              
                              <div className={`text-xs ${isAvailable ? 'text-green-600' : 'text-gray-500'}`}>
                                Used {coupon.currentUses}/{coupon.maxUses || '∞'} times
                                                                 {coupon.expiresAt && (
                                   <span className="ml-4">
                                     Expires: {new Date(coupon.expiresAt!).toLocaleDateString()}
                                   </span>
                                 )}
                              </div>
                            </div>
                          </div>
                        </div>
                      );
                    })}
                    
                    <div className="mt-6 p-4 bg-blue-50 border border-blue-200 rounded-lg">
                      <h4 className="font-medium text-blue-900 mb-2">💡 How to earn more coupons:</h4>
                      <ul className="text-sm text-blue-800 space-y-1">
                        <li>• Attend events and fill out feedback forms</li>
                        <li>• Participate in career events for special discounts</li>
                        <li>• Check back regularly for new coupon opportunities</li>
                      </ul>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
} 